version: '3.8'

services:
  db:
    image: postgres:17
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: Stepik
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - db
    ports:
      - "8000:8000"
    environment:
      POSTGRES_HOST: db
      POSTGRES_DB: Stepik
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_PORT: 5432
    networks:
      - app-network

  nginx:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    restart: always
    depends_on:
      - backend
    # Порты убраны. В Coolify в поле Domains напиши http://твой_ip
    networks:
      - app-network
      - coolify
    labels:
      - "coolify.port=80"

networks:
  app-network:
    driver: bridge
  coolify:
    external: true

volumes:
  pgdata:
